# Generated by Django 4.0.1 on 2022-02-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220205_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
